"""Plugin implementation for Mistral Voxtral transcription through vLLM server

Docs: https://cj-mills.github.io/cjm-transcription-plugin-voxtral-vllmplugin.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/plugin.ipynb.

# %% auto #0
__all__ = ['VLLMServer', 'VoxtralVLLMPluginConfig', 'VoxtralVLLMPlugin']

# %% ../nbs/plugin.ipynb #77c18907
import json
import time
import os
import sys
from uuid import uuid4
import logging
from pathlib import Path
from dataclasses import dataclass, field
from dataclasses import replace as dataclass_replace
from typing import Callable, Dict, Any, Optional, List, Union, Generator, ClassVar
import tempfile
import warnings
from threading import Thread
import subprocess
import time
import requests
import atexit
import signal
import threading
import queue
import re
from datetime import datetime

from fastcore.basics import patch

import numpy as np
import soundfile as sf

try:
    from openai import OpenAI
    OPENAI_AVAILABLE = True
except ImportError:
    OPENAI_AVAILABLE = False

try:
    from mistral_common.protocol.transcription.request import TranscriptionRequest
    from mistral_common.protocol.instruct.chunk import RawAudio
    from mistral_common.audio import Audio
    MISTRAL_COMMON_AVAILABLE = True
except ImportError:
    MISTRAL_COMMON_AVAILABLE = False
    
from cjm_transcription_plugin_system.plugin_interface import TranscriptionPlugin
from cjm_transcription_plugin_system.core import TranscriptionResult
from cjm_transcription_plugin_system.storage import TranscriptionStorage
from cjm_plugin_system.utils.hashing import hash_file, hash_bytes, hash_dict_canonical
from cjm_plugin_system.core.errors import (
    PluginInputError, PluginFatalError, PluginTransientError,
    PluginResourceError, ResourceShortfall,
)
from cjm_plugin_system.utils.validation import (
    dict_to_config, config_to_dict, validate_config, dataclass_to_jsonschema,
    SCHEMA_TITLE, SCHEMA_DESC, SCHEMA_MIN, SCHEMA_MAX, SCHEMA_ENUM
)
from cjm_plugin_system.core.interface import RELOAD_TRIGGER, EnvVarSpec  # CR-4 reload metadata + CR-12 worker-env (Track 19)

from cjm_transcription_plugin_voxtral_vllm.meta import (
    get_plugin_metadata
)

# %% ../nbs/plugin.ipynb #d38c0984
import subprocess
import time
import requests
import atexit
import signal
import threading
import queue
import re
from contextlib import contextmanager
from typing import Optional, Callable, List
from datetime import datetime

class VLLMServer:
    """vLLM server manager for Voxtral models."""

    def __init__(
        self,
        model: str = "mistralai/Voxtral-Mini-3B-2507", # Model name to serve
        port: int = 8000, # Port for the server
        host: str = "0.0.0.0", # Host address to bind to
        gpu_memory_utilization: float = 0.85, # Fraction of GPU memory to use
        log_level: str = "INFO", # Logging level (DEBUG, INFO, WARNING, ERROR)
        capture_logs: bool = True, # Whether to capture and display server logs
        **kwargs # Additional vLLM server arguments
    ):
        self.model = model
        self.port = port
        self.host = host
        self.base_url = f"http://localhost:{self.port}"
        self.process: Optional[subprocess.Popen] = None
        self.capture_logs = capture_logs
        self.log_level = log_level
        
        # Log management
        self.log_queue = queue.Queue()
        self.log_thread = None
        self.stop_logging = threading.Event()
        self.log_callbacks: List[Callable] = []
        
        # Build command
        # Use sys.executable instead of "python"
        # This ensures we use the exact same environment the worker is running in
        self.cmd = [
            sys.executable, "-m", "vllm.entrypoints.openai.api_server",
            "--model", model,
            "--port", str(self.port),
            "--host", host,
            "--gpu-memory-utilization", str(gpu_memory_utilization),
            "--tokenizer-mode", "mistral",
            "--config-format", "mistral",
            "--load-format", "mistral",
        ]
        
        for key, value in kwargs.items():
            self.cmd.extend([f"--{key.replace('_', '-')}", str(value)])
    
    def add_log_callback(
        self, 
        callback: Callable[[str], None] # Function that receives log line strings
    ) -> None: # Returns nothing
        """Add a callback function to receive each log line."""
        self.log_callbacks.append(callback)
    
    def _process_log_line(
        self, 
        line: str # Log line to process
    ) -> None: # Returns nothing
        """Process a single log line."""
        if not line.strip():
            return
        
        # Add timestamp if not present
        if not re.match(r'^\d{2}-\d{2} \d{2}:\d{2}:\d{2}', line):
            timestamp = datetime.now().strftime("%m-%d %H:%M:%S")
            line = f"{timestamp} {line}"
        
        # Store in queue for retrieval
        self.log_queue.put(line)
        
        # Call callbacks
        for callback in self.log_callbacks:
            try:
                callback(line)
            except Exception as e:
                print(f"Error in log callback: {e}")
        
        # Print if we're capturing logs
        if self.capture_logs:
            print(line)
    
    def _log_reader(
        self, 
        pipe, # Pipe to read from
        pipe_name: str # Name of the pipe (stdout/stderr)
    ) -> None: # Returns nothing
        """Read logs from a pipe in a separate thread."""
        for line in iter(pipe.readline, ''):
            if self.stop_logging.is_set():
                break
            if line:
                # Add pipe identifier for debugging
                if pipe_name == "stderr" and "INFO" in line:
                    # Most INFO logs come through stderr in vLLM
                    self._process_log_line(line.strip())
                elif pipe_name == "stdout":
                    self._process_log_line(line.strip())
    
    def start(
        self,
        wait_for_ready: bool = True,                                 # Wait for server to be ready before returning
        show_progress: bool = True,                                  # Show progress indicators during startup
        report_progress: Optional[Callable[[float, str], None]] = None,  # Substrate's PluginInterface.report_progress; defeats prefetch stall detection
    ) -> None: # Returns nothing
        """Start the vLLM server.

        Session A 2026-05-27: dropped the wall-clock `timeout` argument — startup
        time is unbounded (model download + CUDA graph capture), and any operator-
        set value would either race a slow network or be conservatively huge. The
        substrate's proxy.prefetch now drives stall detection via the
        report_progress callback (no progress update for SubstrateConfig.
        prefetch_stall_threshold_seconds → substrate SIGTERMs the worker). When
        report_progress is None we still loop forever; only the OS / operator can
        abort.
        """
        if self.is_running():
            print("Server is already running")
            return
        
        print(f"Starting vLLM server with model {self.model}...")
        print(f"Command: {' '.join(self.cmd)}") # Log the command for debugging
        
        # Start process with pipes for output capture
        self.process = subprocess.Popen(
            self.cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            bufsize=1,  # Line buffered
            universal_newlines=True,
            # Removed preexec_fn as it can be unstable in some nested process scenarios
            # preexec_fn=lambda: signal.signal(signal.SIGINT, signal.SIG_IGN)
        )
        
        # Start log reading threads
        self.stop_logging.clear()
        
        if self.capture_logs:
            # Create threads for reading stdout and stderr
            stdout_thread = threading.Thread(
                target=self._log_reader,
                args=(self.process.stdout, "stdout"),
                daemon=True
            )
            stderr_thread = threading.Thread(
                target=self._log_reader,
                args=(self.process.stderr, "stderr"),
                daemon=True
            )
            stdout_thread.start()
            stderr_thread.start()
        
        # Register cleanup on exit
        atexit.register(self.stop)
        
        if wait_for_ready:
            self._wait_for_server(show_progress, report_progress=report_progress)
    
    def _wait_for_server(
        self,
        show_progress: bool,                                          # Whether to print phase indicators
        report_progress: Optional[Callable[[float, str], None]] = None,  # Substrate's report_progress callback; called on every log line
    ) -> None: # Returns nothing
        """Wait for server to be ready to accept requests.

        Session A 2026-05-27: no wall-clock timeout — loops until the server's
        /health returns 200 OR the vLLM Popen exits non-zero. On each log line
        consumed, calls report_progress(0.5, phase_or_line_summary) — the
        substrate's proxy.prefetch polls /progress and SIGTERMs the worker if
        the (progress, message) tuple stops advancing for
        SubstrateConfig.prefetch_stall_threshold_seconds. Operator-tunable
        substrate-side; the plugin no longer carries a server_startup_timeout
        field (operators were racing arbitrary timeouts against network speeds
        for the model download).
        """
        last_status = ""
        last_line_summary: Optional[str] = None
        start_time = time.time()
        phases = {
            "detected platform": "🔍 Detecting platform...",
            "Loading model": "📦 Loading model weights...",
            "downloading weights": "⬇️ Downloading model weights...",
            "Loading weights took": "✅ Model weights loaded",
            "Graph capturing": "📊 Capturing CUDA graphs...",
            "Graph capturing finished": "✅ CUDA graphs ready",
            "Starting vLLM API server": "🚀 Starting API server...",
            "Available routes": "✅ Server ready!",
        }

        while True:
            # Drain a log line if available; advance phase.
            try:
                log_line = self.log_queue.get_nowait()
            except queue.Empty:
                log_line = None
            if log_line:
                detected_status: Optional[str] = None
                for key, status_msg in phases.items():
                    if key in log_line:
                        detected_status = status_msg
                        break
                if show_progress and detected_status and detected_status != last_status:
                    print(f"\n  {detected_status}")
                    last_status = detected_status
                last_line_summary = detected_status or log_line[:120]

            # Heartbeat: report progress EVERY iteration with elapsed time embedded
            # in the message so the (progress, message) tuple ALWAYS advances. This
            # is the stall-detection contract — substrate.proxy.prefetch SIGTERMs
            # the worker only when /progress STOPS advancing (the loop itself wedged
            # / worker died). vLLM is silent for many seconds during HF Hub
            # download setup; without this heartbeat, the substrate would SIGTERM
            # a perfectly-fine plugin just because vLLM hadn't started emitting
            # logs yet.
            if report_progress is not None:
                elapsed = time.time() - start_time
                summary = last_line_summary or last_status or "awaiting vLLM startup logs"
                try:
                    report_progress(0.5, f"vLLM ({elapsed:.1f}s): {summary}")
                except Exception:
                    # report_progress is best-effort plumbing; never let it
                    # break server startup.
                    pass

            # Ready check.
            try:
                response = requests.get(f"{self.base_url}/health", timeout=1)
                if response.status_code == 200:
                    print(f"\n✅ vLLM server is ready at {self.base_url}")
                    if report_progress is not None:
                        try:
                            report_progress(1.0, f"vLLM server ready at {self.base_url}")
                        except Exception:
                            pass
                    return
            except requests.exceptions.RequestException:
                pass

            # Crash reporting (substrate's Popen.poll-on-crash check).
            if self.process.poll() is not None:
                stdout, stderr = self.process.communicate()
                error_msg = f"Server process exited with code {self.process.poll()}"
                if stdout: error_msg += f"\n[STDOUT]:\n{stdout}"
                if stderr: error_msg += f"\n[STDERR]:\n{stderr}"
                print(error_msg)  # Tee to worker log
                # SG-47: server process exited during startup — fatal; operator must fix
                raise PluginFatalError(error_msg)

            time.sleep(0.5)
    
    def stop(self) -> None: # Returns nothing
        """Stop the vLLM server."""
        if self.process and self.process.poll() is None:
            print("Stopping vLLM server...")
            
            # Signal threads to stop
            self.stop_logging.set()
            
            # Terminate process
            self.process.terminate()
            try:
                self.process.wait(timeout=10)
            except subprocess.TimeoutExpired:
                print("Force killing server...")
                self.process.kill()
                self.process.wait()
            
            self.process = None
            print("Server stopped")
    
    def restart(self) -> None: # Returns nothing
        """Restart the server."""
        self.stop()
        time.sleep(2)
        self.start()
    
    def is_running(self) -> bool: # True if server is running and responsive
        """Check if server is running and responsive."""
        # First check if process exists and hasn't exited
        if self.process is None or self.process.poll() is not None:
            return False
        
        # Try to connect to the server
        try:
            response = requests.get(f"{self.base_url}/health", timeout=1)
            if response.status_code == 200:
                # print(f"\n✅ vLLM server is ready at {self.base_url}")
                return True
            else:
                print(f"\n❌ vLLM server is not ready at {self.base_url}")
                return False
        except requests.exceptions.RequestException as e:
            print(f"\n❌ The following exception occurred: {e}")
            return False
    
    def get_recent_logs(
        self, 
        n: int = 100 # Number of recent log lines to retrieve
    ) -> List[str]: # List of recent log lines
        """Get the most recent n log lines."""
        logs = []
        while not self.log_queue.empty() and len(logs) < n:
            try:
                logs.append(self.log_queue.get_nowait())
            except queue.Empty:
                break
        return logs
    
    def get_metrics_from_logs(self) -> dict: # Dictionary with performance metrics
        """Parse recent logs to extract performance metrics."""
        metrics = {
            "prompt_throughput": 0.0,
            "generation_throughput": 0.0,
            "running_requests": 0,
            "waiting_requests": 0,
            "gpu_kv_cache_usage": 0.0,
            "prefix_cache_hit_rate": 0.0,
        }
        
        # Look for metric lines in recent logs
        recent_logs = self.get_recent_logs(50)
        for log in recent_logs:
            if "Avg prompt throughput:" in log:
                # Parse metrics line
                match = re.search(r'Avg prompt throughput: ([\d.]+) tokens/s', log)
                if match:
                    metrics["prompt_throughput"] = float(match.group(1))
                
                match = re.search(r'Avg generation throughput: ([\d.]+) tokens/s', log)
                if match:
                    metrics["generation_throughput"] = float(match.group(1))
                
                match = re.search(r'Running: (\d+) reqs', log)
                if match:
                    metrics["running_requests"] = int(match.group(1))
                
                match = re.search(r'Waiting: (\d+) reqs', log)
                if match:
                    metrics["waiting_requests"] = int(match.group(1))
                
                match = re.search(r'GPU KV cache usage: ([\d.]+)%', log)
                if match:
                    metrics["gpu_kv_cache_usage"] = float(match.group(1))
                
                match = re.search(r'Prefix cache hit rate: ([\d.]+)%', log)
                if match:
                    metrics["prefix_cache_hit_rate"] = float(match.group(1))
                
                break  # Use the most recent metrics
        
        return metrics
    
    def tail_logs(
        self, 
        follow: bool = True, # Continue displaying new logs as they arrive
        n: int = 10 # Number of initial lines to display
    ) -> None: # Returns nothing
        """Tail the server logs (similar to tail -f)."""
        # Display recent logs
        recent = self.get_recent_logs(n)
        for line in recent:
            print(line)
        
        if follow:
            print("\n--- Following logs (Ctrl+C to stop) ---\n")
            try:
                while self.is_running():
                    if not self.log_queue.empty():
                        print(self.log_queue.get())
                    else:
                        time.sleep(0.1)
            except KeyboardInterrupt:
                print("\n--- Stopped following logs ---")
    
    def __enter__(self):
        """Context manager entry."""
        self.start()
        return self
    
    def __exit__(self, exc_type, exc_val, exc_tb):
        """Context manager exit."""
        self.stop()

# %% ../nbs/plugin.ipynb #config-dataclass
@dataclass
class VoxtralVLLMPluginConfig:
    """Configuration for Voxtral VLLM transcription plugin."""
    model_id:str = field(
        default="mistralai/Voxtral-Mini-3B-2507",
        metadata={
            SCHEMA_TITLE: "Model ID",
            SCHEMA_DESC: "Voxtral model to use. Mini is faster, Small is more accurate.",
            SCHEMA_ENUM: ["mistralai/Voxtral-Mini-3B-2507", "mistralai/Voxtral-Small-24B-2507"],
            RELOAD_TRIGGER: "vllm_server",  # CR-4: model change requires vLLM server respawn
        }
    )
    device:str = field(
        default="cuda",
        metadata={
            SCHEMA_TITLE: "Device",
            SCHEMA_DESC: "Device for inference (will use CUDA if available)"
        }
    )
    server_mode:str = field(
        default="managed",
        metadata={
            SCHEMA_TITLE: "Server Mode",
            SCHEMA_DESC: "'managed': plugin manages server lifecycle, 'external': connect to existing server",
            SCHEMA_ENUM: ["managed", "external"],
            RELOAD_TRIGGER: "vllm_server",  # CR-4: managed<->external switch rebuilds server + client
        }
    )
    server_url:str = field(
        default="http://localhost:8000",
        metadata={
            SCHEMA_TITLE: "Server URL",
            SCHEMA_DESC: "vLLM server URL (for external mode)",
            RELOAD_TRIGGER: "vllm_server",  # CR-4: external client base_url change rebuilds client; no-op for managed
        }
    )
    server_port:int = field(
        default=8000,
        metadata={
            SCHEMA_TITLE: "Server Port",
            SCHEMA_DESC: (
                "Port for managed vLLM server. CR-10 multi-instance: when running "
                "multiple managed vLLM instances simultaneously (e.g., comparison "
                "feature loading two model variants), set a UNIQUE port per instance "
                "via the substrate's load_plugin(..., new_instance=True, "
                "config={'server_port': N}) call — sharing a port between instances "
                "produces 'port already in use' on the second server's startup."
            ),
            SCHEMA_MIN: 1024,
            SCHEMA_MAX: 65535,
            RELOAD_TRIGGER: "vllm_server",  # CR-4: port change requires managed-server respawn
        }
    )
    gpu_memory_utilization:float = field(
        default=0.85,
        metadata={
            SCHEMA_TITLE: "GPU Memory Utilization",
            SCHEMA_DESC: "Fraction of GPU memory to use (managed mode)",
            SCHEMA_MIN: 0.1,
            SCHEMA_MAX: 1.0,
            RELOAD_TRIGGER: "vllm_server",  # CR-4: vLLM allocator is fixed at server boot
        }
    )
    max_model_len:int = field(
        default=32768,
        metadata={
            SCHEMA_TITLE: "Max Model Length",
            SCHEMA_DESC: "Maximum sequence length for the model",
            SCHEMA_MIN: 1024,
            SCHEMA_MAX: 131072,
            RELOAD_TRIGGER: "vllm_server",  # CR-4: vLLM KV-cache shape fixed at server boot
        }
    )
    language:Optional[str] = field(
        default="en",
        metadata={
            SCHEMA_TITLE: "Language",
            SCHEMA_DESC: "Language code for transcription (e.g., 'en', 'es', 'fr')"
        }
    )
    temperature:float = field(
        default=0.0,
        metadata={
            SCHEMA_TITLE: "Temperature",
            SCHEMA_DESC: "Temperature for sampling (0.0 for deterministic)",
            SCHEMA_MIN: 0.0,
            SCHEMA_MAX: 2.0
        }
    )
    auto_start_server:bool = field(
        default=True,
        metadata={
            SCHEMA_TITLE: "Auto Start Server",
            SCHEMA_DESC: "Automatically start server on first use (managed mode)"
        }
    )
    capture_server_logs:bool = field(
        default=True,
        metadata={
            SCHEMA_TITLE: "Capture Server Logs",
            SCHEMA_DESC: "Capture vLLM server logs (managed mode)",
            RELOAD_TRIGGER: "vllm_server",  # CR-4: log-reader threads are wired at VLLMServer.__init__
        }
    )
    dtype:str = field(
        default="auto",
        metadata={
            SCHEMA_TITLE: "Data Type",
            SCHEMA_DESC: "Data type for model weights",
            SCHEMA_ENUM: ["auto", "half", "float16", "bfloat16", "float32"],
            RELOAD_TRIGGER: "vllm_server",  # CR-4: weight dtype baked at server boot
        }
    )
    tensor_parallel_size:int = field(
        default=1,
        metadata={
            SCHEMA_TITLE: "Tensor Parallel Size",
            SCHEMA_DESC: "Number of GPUs for tensor parallelism",
            SCHEMA_MIN: 1,
            SCHEMA_MAX: 8,
            RELOAD_TRIGGER: "vllm_server",  # CR-4: TP topology fixed at server boot
        }
    )

# %% ../nbs/plugin.ipynb #7ff4bbf9
class VoxtralVLLMPlugin(TranscriptionPlugin):
    """Mistral Voxtral transcription plugin via vLLM server."""
    
    config_class = VoxtralVLLMPluginConfig

    # Track 19 (CR-12 worker-env model): worker spawn env declared on the class.
    # CUDA_VISIBLE_DEVICES + VLLM_ATTENTION_BACKEND are static; HF_HOME is templated to
    # the substrate models dir (vLLM pulls Voxtral weights from HF Hub). The substrate
    # resolves + injects these at Popen.
    WORKER_ENV: ClassVar[List[EnvVarSpec]] = [
        EnvVarSpec(
            name="CUDA_VISIBLE_DEVICES",
            default="0",
            label="GPU Device",
            description="Which GPU index the worker uses.",
        ),
        EnvVarSpec(
            name="VLLM_ATTENTION_BACKEND",
            default="FLASHINFER",
            label="vLLM Attention Backend",
            description="vLLM attention kernel backend.",
        ),
        EnvVarSpec(
            name="HF_HOME",
            default="${CJM_MODELS_DIR}/huggingface",
            label="HF Cache Directory",
            description="HuggingFace Hub cache root (templated to the substrate models dir).",
        ),
    ]
    
    def __init__(self):
        """Initialize the Voxtral VLLM plugin with default configuration."""
        self.logger = logging.getLogger(f"{__name__}.{type(self).__name__}")
        self.config: VoxtralVLLMPluginConfig = None
        self.server: Optional[VLLMServer] = None
        self.client: Optional[OpenAI] = None
        self.model_id: Optional[str] = None
        self.storage: Optional[TranscriptionStorage] = None
    
    @property
    def name(self) -> str:  # The plugin name identifier
        """Get the plugin name identifier (single source of truth: meta.py)."""
        return get_plugin_metadata()["name"]

    @property
    def version(self) -> str:  # The plugin version string
        """Get the plugin version string (single source of truth: meta.py / __version__)."""
        return get_plugin_metadata()["version"]
    
    @property
    def supported_formats(self) -> List[str]: # List of supported audio formats
        """Get the list of supported audio file formats."""
        return ["wav", "mp3", "flac", "m4a", "ogg", "webm", "mp4", "avi", "mov"]
    
    def get_current_config(self) -> Dict[str, Any]: # Current configuration as dictionary
        """Return current configuration state."""
        if not self.config:
            return {}
        return config_to_dict(self.config)

    def get_config_schema(self) -> Dict[str, Any]: # JSON Schema for configuration
        """Return JSON Schema for UI generation."""
        return dataclass_to_jsonschema(VoxtralVLLMPluginConfig)

    @staticmethod
    def get_config_dataclass() -> VoxtralVLLMPluginConfig: # Configuration dataclass
        """Return dataclass describing the plugin's configuration options."""
        return VoxtralVLLMPluginConfig
    


    def initialize(
        self,
        config: Optional[Any] = None  # Configuration dataclass, dict, or None
    ) -> None:
        """First-time setup. CR-4: the manual server-restart diff-checks are
        replaced by declarative RELOAD_TRIGGER metadata; the substrate's
        reconfigure path fires `_release_vllm_server` then re-applies config
        via `_apply_config`."""
        self._apply_config(config)

        # One-time storage initialization (DB path is install-fixed, not config-derived).
        db_path = get_plugin_metadata()["db_path"]
        self.storage = TranscriptionStorage(db_path)

        self.logger.info(
            f"Initialized Voxtral VLLM plugin with model '{self.model_id}' "
            f"in {self.config.server_mode} mode"
        )


    
    


    def execute(
        self,
        audio: Union[str, Path], # Audio data or path to audio file to transcribe
        **kwargs # Additional arguments to override config
    ) -> TranscriptionResult: # Transcription result with text and metadata
        """Transcribe audio using Voxtral via vLLM."""
        # Prepare audio file
        audio_path = self._prepare_audio(audio)
        temp_file_created = False  # caller provides a model-ready path; plugin never creates a temp file

        # Hash the audio file (content) for the cache key
        audio_hash = hash_file(audio_path)

        # Hash the effective config for cache keying. CR-15: config_hash derives from
        # self.config (the effective config); the per-call kwargs config-overrides below
        # are NOT reflected here — that override path predates the substrate overhaul and
        # is slated for removal (candidate CR-15 / project_execute_invocation_contract_gap).
        config_hash = hash_dict_canonical(config_to_dict(self.config))

        # 1. Cache check (content-correct: audio_path + audio_hash + config_hash), before
        #    starting the vLLM server so a pure cache hit avoids the server spin-up entirely.
        if not kwargs.get("force", False):
            cached = self.storage.get_cached(str(audio), audio_hash, config_hash)
            if cached:
                self.logger.info(f"Using cached transcription for {audio}")
                return TranscriptionResult(
                    text=cached.text,
                    confidence=None,
                    segments=cached.segments,
                    metadata=cached.metadata,
                )

        # 2. Cache miss — ensure the vLLM server is running, then transcribe
        self._ensure_server_running()

        try:
            # Get config values, allowing kwargs overrides
            # CR-15: these per-call config-overrides bypass reconfigure/persistence/validation/
            # config_hash and are slated for removal; provenance kwargs (job_id/source_*_time) stay.
            language = kwargs.get("language", self.config.language)
            temperature = kwargs.get("temperature", self.config.temperature)
            
            # Prepare inputs using mistral_common
            self.logger.info(f"Processing audio with Voxtral {self.model_id} via vLLM")
            
            input_audio = Audio.from_file(audio_path, strict=False)
            input_audio = RawAudio.from_audio(input_audio)
            
            req = TranscriptionRequest(
                model=self.model_id,
                audio=input_audio,
                language=language or "en",
                temperature=temperature
            ).to_openai(exclude=("top_p", "seed", "target_streaming_delay_ms"))
            
            # Get transcription from vLLM server. SG-47 Track B follow-up: if the
            # vLLM subprocess dies during this request (typically CUDA OOM in the
            # vLLM server), classify as PluginResourceError so substrate CR-7
            # reactive-retry can reload + retry.
            try:
                response = self.client.audio.transcriptions.create(**req)
            except Exception as e:
                self._check_vllm_subprocess_death(e, context="transcription request")
                raise  # Server alive (or external mode); substrate default-classifies
            
            # Create transcription result
            transcription_result = TranscriptionResult(
                text=response.text.strip(),
                confidence=None,  # vLLM doesn't provide confidence scores
                segments=None,  # vLLM doesn't provide segments by default
                metadata={
                    "model": self.model_id,
                    "language": language or "en",
                    "server_mode": self.config.server_mode,
                    "temperature": temperature,
                }
            )
            
            # Hash the transcription output
            text_hash = hash_bytes(transcription_result.text.encode())
            
            # Save to standardized storage (helper logs success/failure; never raises)
            job_id = kwargs.get("job_id", str(uuid4()))
            self.storage.save_with_logging(
                job_id=job_id,
                audio_path=str(audio),
                audio_hash=audio_hash,
                config_hash=config_hash,
                text=transcription_result.text,
                text_hash=text_hash,
                segments=transcription_result.segments,
                metadata=transcription_result.metadata,
                logger=self.logger,
            )
            
            self.logger.info(f"Transcription completed: {len(response.text.split())} words")
            return transcription_result
            
        finally:
            # Clean up temporary file if created
            if temp_file_created:
                try:
                    Path(audio_path).unlink()
                except Exception:
                    pass

# %% ../nbs/plugin.ipynb #m-apply-config
@patch
def _apply_config(
    self:VoxtralVLLMPlugin,
    config: Optional[Any] = None  # Configuration dataclass, dict, or None
) -> None:
    """CR-4: apply config + (re)build the VLLMServer (managed mode) and OpenAI client.

    No-heavy-resource setup other than constructing the VLLMServer wrapper —
    the actual subprocess spawn is deferred to `prefetch()` / first execute
    via `_ensure_server_running()`. Called by `initialize` for first-time
    setup and by the substrate's `reconfigure_with_triggers` delta path
    AFTER `_release_vllm_server` has fired for any changed RELOAD_TRIGGER
    field. The manual diff-and-reload block that used to live in
    `initialize()` is replaced by the declarative RELOAD_TRIGGER metadata
    on the config dataclass fields above (CR-4 Track 5).
    """
    self.config = dict_to_config(VoxtralVLLMPluginConfig, config or {})
    self.model_id = self.config.model_id

    # Build VLLMServer wrapper for managed mode (subprocess spawn happens later).
    if self.config.server_mode == "managed":
        if self.server is None:
            self.server = VLLMServer(
                model=self.model_id,
                port=self.config.server_port,
                gpu_memory_utilization=self.config.gpu_memory_utilization,
                max_model_len=self.config.max_model_len,
                capture_logs=self.config.capture_server_logs,
                dtype=self.config.dtype,
                tensor_parallel_size=self.config.tensor_parallel_size,
            )
        server_url = f"http://localhost:{self.config.server_port}"
    else:
        # External-server mode: caller manages the vLLM server lifecycle.
        server_url = self.config.server_url

    # OpenAI-compatible client (vLLM's server speaks this protocol).
    # Lazy: rebuild only when _release_vllm_server has cleared it. Since
    # every base_url-affecting field (server_mode/server_url/server_port)
    # is a RELOAD_TRIGGER, the substrate's reconfigure path always passes
    # through _release_vllm_server (which sets self.client = None) before
    # re-entering _apply_config — so a None check is sufficient + avoids
    # client churn on unrelated config changes (e.g. temperature).
    if self.client is None:
        self.client = OpenAI(
            api_key="EMPTY",  # vLLM doesn't require an API key
            base_url=f"{server_url}/v1",
        )

# %% ../nbs/plugin.ipynb #m-release-vllm-server
@patch
def _release_vllm_server(self:VoxtralVLLMPlugin) -> None:
    """CR-4: release the managed vLLM server subprocess + the OpenAI client.

    Called by the substrate's `reconfigure_with_triggers` BEFORE
    `_apply_config` rebuilds them, whenever any RELOAD_TRIGGER="vllm_server"
    field changes. Also called from `on_disable()` (operator-initiated
    disable while the worker stays alive) and `cleanup()` (worker unload).
    Idempotent: safe to call when the server is already stopped or the
    client is already None.
    """
    if self.server is not None:
        if self.server.is_running():
            self.logger.info("Releasing managed vLLM server subprocess")
            self.server.stop()
        self.server = None
    # Client recreation is cheap; drop it eagerly so any stale base_url
    # / api_key state can't survive into the next _apply_config.
    self.client = None

# %% ../nbs/plugin.ipynb #m-prefetch
@patch
def prefetch(self:VoxtralVLLMPlugin) -> None:
    """CR-4 (SG-19): eagerly spawn the managed vLLM server so the first
    execute() doesn't pay the startup cost (model load, CUDA graph capture,
    weight download for cold caches). No-op in external mode (caller
    manages the server). Idempotent via `_ensure_server_running`'s
    is_running() check.

    Session A 2026-05-27: passes `self.report_progress` (inherited from
    PluginInterface) through to VLLMServer so substrate.proxy.prefetch's
    stall detection sees progress events on every vLLM log line. Replaces
    the prior wall-clock `server_startup_timeout` config field — operators
    no longer race network speeds against an arbitrary timeout value.
    """
    if self.config and self.config.server_mode == "managed":
        self._ensure_server_running(report_progress=self.report_progress)

# %% ../nbs/plugin.ipynb #m-on-disable
@patch
def on_disable(self:VoxtralVLLMPlugin) -> None:
    """CR-2: release the vLLM server subprocess when the operator disables
    the plugin while keeping the worker alive. Re-enable + next execute
    lazy-respawns via `_ensure_server_running`."""
    self._release_vllm_server()

# %% ../nbs/plugin.ipynb #m-ensure-server-running
@patch
def _ensure_server_running(
    self:VoxtralVLLMPlugin,
    report_progress: Optional[Callable[[float, str], None]] = None,  # Session A: substrate-driven stall detection callback
) -> None:
    """Ensure the vLLM server is running (for managed mode).

    Session A 2026-05-27: forwards `report_progress` to `VLLMServer.start`
    so substrate.proxy.prefetch's stall detection sees progress events
    while vLLM loads the model + captures CUDA graphs. Without a callback
    (e.g., when called from `execute()` rather than `prefetch()`), startup
    still loops to completion — just without progress reporting.
    """
    if self.config.server_mode == "managed" and self.server:
        if not self.server.is_running():
            self.logger.warning("vLLM server is not running")
            if self.config.auto_start_server:
                self.logger.info("Starting vLLM server...")
                self.server.start(
                    wait_for_ready=True,
                    show_progress=self.config.capture_server_logs,
                    report_progress=report_progress,
                )
            else:
                # SG-47: config combo (auto_start_server=False, no external server)
                # is operator-misconfigured at execute-time; fatal until reconfigured.
                raise PluginFatalError("vLLM server is not running and auto_start_server is disabled")
    elif self.config.server_mode == "external":
        # Check if external server is accessible
        try:
            response = requests.get(f"{self.config.server_url}/health", timeout=5)
            if response.status_code != 200:
                # SG-47: external server unhealthy — transient; substrate retry plausible
                # if server self-recovers.
                raise PluginTransientError(f"External vLLM server returned status {response.status_code}")
        except requests.exceptions.RequestException as e:
            # SG-47: network failure → transient; substrate retry may succeed.
            raise PluginTransientError(f"Cannot connect to external vLLM server: {e}") from e

# %% ../nbs/plugin.ipynb #m-prepare-audio
@patch
def _prepare_audio(
    self:VoxtralVLLMPlugin,
    audio: Union[str, Path] # Path to a decodable audio file
) -> str: # The audio file path
    """Validate the audio input and return it as a path string.

    The caller (orchestration / proxy) guarantees a model-ready audio file;
    in-memory preparation is no longer a plugin responsibility."""
    if isinstance(audio, (str, Path)):
        return str(audio)
    raise PluginInputError(  # SG-47: typed input-validation (multi-inherits ValueError)
        f"Unsupported audio input type: {type(audio)}; expected a file path (str or Path)",
        fields_invalid=["audio"],
    )

# %% ../nbs/plugin.ipynb #m-check-vllm-subprocess-death
@patch
def _check_vllm_subprocess_death(
    self:VoxtralVLLMPlugin,
    original_exc: BaseException,  # The exception caught from the HTTP call
    context: str,                 # Human-readable context for the error message
) -> None:
    """SG-47 Track B follow-up: classify HTTP failures by vLLM subprocess state.

    If the managed vLLM server subprocess (`self.server.process`) has exited,
    the request failure is most likely due to vLLM dying — typically
    CUDA OOM in the vLLM server during model inference. Raises
    `PluginResourceError` so substrate's CR-7 reactive-retry can reload
    + retry. If the process is alive (or external-server mode without
    a managed process), returns without raising — caller re-raises the
    original exception which the substrate's default classify_exception()
    MRO walk handles via CR-5.

    Analogous to CR-7's `_check_worker_death` Track A classifier in the
    substrate, but applied to the vLLM subprocess (one process layer
    deeper than the plugin worker). The substrate sees a clean
    PluginResourceError from the plugin worker rather than the worker
    itself crashing.
    """
    # SG-47 Track B follow-up fix: the prior code referenced `self.process`,
    # but the plugin doesn't own a Popen directly — the managed-mode
    # `VLLMServer` wrapper does. Access via `self.server.process`; external
    # mode (no managed server) returns without raising.
    server = self.server
    if server is None or server.process is None:
        return
    rc = server.process.poll()
    if rc is not None:
        raise PluginResourceError(
            f"vLLM server subprocess died during {context} "
            f"(exit code {rc}): {original_exc}. "
            f"Most likely CUDA OOM in the vLLM server subprocess.",
            resource_shortfall=ResourceShortfall(
                resource='gpu_vram_mb',
                needed=0.0,     # Server is dead — can't query exact numbers
                available=0.0,  # Same; substrate uses presence of shortfall + CR-7 retry
            ),
        ) from original_exc

# %% ../nbs/plugin.ipynb #m-is-available
@patch
def is_available(self:VoxtralVLLMPlugin) -> bool: # True if vLLM and dependencies are available
    """Check if vLLM and required dependencies are available."""
    if not OPENAI_AVAILABLE:
        return False
    if not MISTRAL_COMMON_AVAILABLE:
        return False

    # Check if vLLM is installed
    try:
        import vllm
        return True
    except ImportError:
        return False

# %% ../nbs/plugin.ipynb #m-cleanup
@patch
def cleanup(self:VoxtralVLLMPlugin) -> None:
    """Release resources on unload. CR-4: delegates to `_release_vllm_server`
    so both the worker-unload path AND the operator-disable / reconfigure
    paths converge on one release implementation."""
    self.logger.info("Cleaning up Voxtral VLLM plugin")
    self._release_vllm_server()
    self.logger.info("Cleanup completed successfully")

# %% ../nbs/plugin.ipynb #99ef2767
@patch
def supports_streaming(
    self: VoxtralVLLMPlugin # The plugin instance
) -> bool: # True if streaming is supported
    """Check if this plugin supports streaming transcription."""
    return True

@patch
def execute_stream(
    self: VoxtralVLLMPlugin, # The plugin instance
    audio: Union[str, Path], # Audio data or path to audio file
    **kwargs # Additional plugin-specific parameters
) -> Generator[str, None, TranscriptionResult]: # Yields text chunks, returns final result
    """Stream transcription results chunk by chunk."""
    # Ensure server is running
    self._ensure_server_running()
    
    # Prepare audio file
    audio_path = self._prepare_audio(audio)
    temp_file_created = False  # caller provides a model-ready path; plugin never creates a temp file
    
    try:
        # Get config values, allowing kwargs overrides
        language = kwargs.get("language", self.config.language)
        temperature = kwargs.get("temperature", self.config.temperature)
        
        # Prepare inputs using mistral_common
        self.logger.info(f"Streaming transcription with Voxtral {self.model_id} via vLLM")
        
        input_audio = Audio.from_file(audio_path, strict=False)
        input_audio = RawAudio.from_audio(input_audio)
        
        req = TranscriptionRequest(
            model=self.model_id,
            audio=input_audio,
            language=language or "en",
            temperature=temperature
        ).to_openai(exclude=("top_p", "seed", "target_streaming_delay_ms"))
        
        # Get streaming transcription from vLLM server. SG-47 Track B follow-up:
        # wrap the initial create() call AND the streaming iteration; vLLM
        # subprocess can die at either point. Mid-stream death surfaces as a
        # streaming-response exception when the next chunk is awaited.
        try:
            response = self.client.audio.transcriptions.create(**req, stream=True)
        except Exception as e:
            self._check_vllm_subprocess_death(e, context="streaming transcription start")
            raise

        # Collect generated text. The iteration may raise mid-stream if the
        # vLLM subprocess crashes; same Track B check applies there.
        generated_text = ""
        try:
            for chunk in response:
                if chunk.choices[0]['delta']['content']:
                    text_chunk = chunk.choices[0]['delta']['content']
                    generated_text += text_chunk
                    yield text_chunk
        except Exception as e:
            self._check_vllm_subprocess_death(e, context="streaming transcription iteration")
            raise
        
        # Return final result
        return TranscriptionResult(
            text=generated_text.strip(),
            confidence=None,
            segments=None,
            metadata={
                "model": self.model_id,
                "language": language or "en",
                "server_mode": self.config.server_mode,
                "temperature": temperature,
                "streaming": True,
            }
        )
        
    finally:
        # Clean up temporary file if created
        if temp_file_created:
            try:
                Path(audio_path).unlink()
            except Exception:
                pass
